name: flake-checker

on:
  push:
    branches: [stream]
  pull_request:

jobs:
  build:
    name: Check inputs and build Nix flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Nix Flake
      uses: DeterminateSystems/flake-checker-action@main
      with:
        ignore-missing-flake-lock: false
        fail-mode: true

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |-
          extra-experimental-features = nix-command flakes ca-derivations

    - name: Build url-info
      run: nix build -L
